apiVersion: v1
kind: Service
metadata:
  name: {{ include "minik8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minik8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "minik8s.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
