replicaCount: 2

nameOverride: ""
fullnameOverride: ""

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "minik8s"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: "minik8s.local"

podSecurityContext: {}

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
